apiVersion: apps/v1
kind: Deployment
metadata:
  name: magical-marinouh-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: magical-marinouh-back
        image: marinouh/flashy:latest
        ports:
        - containerPort: 5000
