name: GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎  The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Display app.py
        run: cat app.py
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --file Dockerfile --tag marinouh/flashy:latest .

      - name: Azure Login and AKS Set Context
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} --service-principal -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.TENANT }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      - name: Push image to Docker Hub
        run: docker push marinouh/flashy:latest

      - name: Update Kubernetes deployment
        run: |
          kubectl apply -f deployment.yaml  
          kubectl apply -f service.yaml 
